export const uiInitialState = {
  showPopUp: false,
  setShowPopUp: () => {},
  popUpTitle: "",
  setPopUpTitle: () => {},
  showContact: false,
  setShowContact: () => {},
  showAbout: false,
  setShowAbout: () => {},
  showProjects: false,
  setShowProjects: () => {},
  showTech: false,
  setShowTech: () => {},
  showResume: false,
  setShowResume: () => {},
  tabs: [],
  addTab: () => {},
  closeTab: () => {},
  toggleTable: () => {},
  showModal: false,
  setShowModal: () => {},
  showOff: false,
  setShowOff: () => {},
  showIn: true,
  setShowIn: () => {},
  projectToShow: {},
  setProjectToShow: () => {},
  showEachProject: false,
  setShowEachProject: () => {},
  reset: () => {},
};
